
services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file: ".env.dev"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  app:
    build: .
    container_name: django_app
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    env_file: ".env.dev"
    depends_on:
      - db


  
